# Generated by Django 3.1.7 on 2021-06-07 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='in_watch',
            field=models.BooleanField(default=False),
        ),
    ]
