# Generated by Django 3.1.7 on 2021-06-07 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20210607_2353'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='in_watch',
        ),
    ]
