# Generated by Django 3.1.7 on 2021-06-07 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_listing_is_closed'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='comment',
            field=models.ManyToManyField(blank=True, related_name='listing', to='auctions.Comment'),
        ),
    ]
